// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://appzhahfveyzbtwakaqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwcHpoYWhmdmV5emJ0d2FrYXF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIwNjAxNDcsImV4cCI6MjA4NzYzNjE0N30.T8gamdsZeW23kfNQJmZUZnXrM8PIXiiVStmGmBaFXLQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});